- README.md
Previous link was the project's link, now changed to the template's link
> chore: update Figma link

- .github/pull_request_template.md
- app/build.gradle.kts
- app/src/androidTest/java/ch/hikemate/app/ExampleInstrumentedTest.kt
- app/src/androidTest/java/ch/hikemate/app/screen/MainScreen.kt
- app/src/main/java/ch/hikemate/app/MainActivity.kt
- app/src/main/java/ch/hikemate/app/SecondActivity.kt
- app/src/main/java/ch/hikemate/app/SimpleData.kt
- app/src/main/java/ch/hikemate/app/resources/C.kt
- app/src/main/java/ch/hikemate/app/ui/theme/Color.kt
- app/src/main/java/ch/hikemate/app/ui/theme/Theme.kt
- app/src/main/java/ch/hikemate/app/ui/theme/Type.kt
- app/src/test/java/ch/hikemate/app/ExampleRobolectricTest.kt
- app/src/test/java/ch/hikemate/app/ExampleUnitTest.kt
- app/src/test/java/ch/hikemate/app/PointTest.kt
- app/src/test/java/ch/hikemate/app/screen/SecondScreen.kt
The project was renamed from FlepMate to HikeMate, leading to token invalidation. Also finally defined the app namespace to change it from the example one.
- Changed the CI tokens
- Added a PR template
> Fixes for organization name changes and adding PR template

- .github/workflows/ci.yml
Added the step to generate the jacoco coverage
The CI job would not create the Jacoco coverage report. Sonar would then always return a 0.0% coverage.
I added the task to generate the Jacoco coverage report in order for Sonar to watch it.
> fix(ci): add the jacoco coverage to sonar

- app/build.gradle.kts
- app/src/main/java/ch/hikemate/app/model/map/ListOfHikeRoutesViewModel.kt
- app/src/test/java/ch/hikemate/app/model/map/ListOfHikeRoutesViewModelTest.kt
- gradle/libs.versions.toml
Implemented the ListOfHikeRoutesViewModel to later retrieve the hike routes from the repository.
The objective was to habe a basic view model with hardcoded values in order to create the map screen.
The following were done:
- Created a `ListOfHikeRoutesViewModel` with the said view model
- Created a `ListOfHikeRoutesViewModelTest` to test it (coverage achieved on the viewmodel: **100%**)
For now, the view model will return hike routes as hardcoded `Strings` ("Route 1", "Route 2", "Route 3"). This will be changed when the `HikeRoute` model will be created.
> feat(map): create the viewmodel for the list of hike routes

- .github/workflows/ci.yml
- app/build.gradle.kts
- app/src/androidTest/java/ch/hikemate/app/navigation/SideBarNavigationTest.kt
- app/src/main/java/ch/hikemate/app/ui/navigation/NavigationActions.kt
- app/src/main/java/ch/hikemate/app/ui/navigation/SideBarNavigation.kt
- app/src/test/java/ch/hikemate/app/navigation/NavigationActionsTest.kt
- gradle/libs.versions.toml
This pull request introduces the core navigation functionality for the **HikeMate** application, setting up the foundation for user flow across various screens.
- **`NavigationActions.kt`**:  
This file defines the primary navigation routes and screen names for the different sections of the app. It provides utility functions for navigating between `TopLevelDestination`s, allowing seamless transitions within the app's structure.
- **`SideBarNavigation.kt`**:  
Introduces a sidebar component that serves as the main navigation UI element. This `ModalNavigationDrawer` is available on most key screens, enabling users to toggle a sidebar menu by clicking the icon in the upper left corner. The menu allows users to navigate through essential parts of the application.
- Modifications were made to …
> feat(navigation): add NavigationActions and the composable SideBarNavigation

- app/build.gradle.kts
- app/src/main/java/ch/hikemate/app/model/route/HikeRoute.kt
- app/src/main/java/ch/hikemate/app/model/route/HikeRoutesRepository.kt
- app/src/main/java/ch/hikemate/app/model/route/HikeRoutesRepositoryOverpass.kt
- app/src/main/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModel.kt
- app/src/test/java/ch/hikemate/app/model/route/HikeRoutesRepositoryOverpassTest.kt
- app/src/test/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModelTest.kt
- gradle/libs.versions.toml
- Feature was added to include a first standard HikeRouteRepository to fetch Hiking routes from Overpass API (Overpass API is the API to extract data from OpenStreetMap)
- Json Parsing is done using a Reader, since otherwise we can easily run into an OOM error when reading the whole body as a String (body can easily reach MB).
Remark: PR is 560 lines long, but a lot of lines are really test data, and I have put detailed comments.
> feat: first implementation of OSM Hiking route API

- app/src/main/java/ch/hikemate/app/model/route/HikeRoutesRepositoryOverpass.kt
There was an int overflow in the overpass api for parsing the id, this PR fix it
> fix: int overflow in overpass api

- app/src/main/java/ch/hikemate/app/ui/navigation/SideBarNavigation.kt
The `SidebarNavigation` composable adds a burger menu button in the top left corner of the screen. For screens such as map, the fact that the button takes a bit of space hovering on the map is not a problem, the user can simply move the map (see attached image below).
However, on screens such as Saved Hikes, the burger menu button could hide the title of the screen or the top composable. This is not the desired behavior (see attached image below).
This PR proposes a quite simple solution to this. `SidebarNavigation` takes a `content` lambda as a parameter. Initially, this `content` lambda took no parameter. I changed it to take a parameter of type `PaddingValues`.
Existing code does not have to change. If there is no parameter in the provided lambda, Kotlin will assume the lambda wants to …
> feat(nav): pass scaffold padding as content param

- app/src/androidTest/java/ch/hikemate/app/navigation/SideBarNavigationTest.kt
- app/src/main/java/ch/hikemate/app/ui/navigation/SideBarNavigation.kt
- app/src/main/res/values/strings.xml
The content description of the button that opens the sidebar (main menu of the app) was hardcoded in the sidebar composable. A content description should
1. Be localized (translatable, i.e. defined in `strings.xml`
2. Describe an action (i.e. "Open sidebar menu" rather than "Sidebar")
I'm not 100% certain for 2., but 1. is certain. Hence this PR simply moves the definition of the sidebar button to `strings.xml`, where it can easily be translated.
It's a very simple PR, but I did not want to include it in the one I'm working on right now (Saved Hikes screen) as I felt it should be a PR of its own given its different nature.
> fix(nav): localize button content description

- app/src/androidTest/java/ch/hikemate/app/ui/map/MapScreenTest.kt
- app/src/main/java/ch/hikemate/app/model/route/HikeRoute.kt
- app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
While testing our app manually, the coaches noticed that when one clicks `Search hikes here` when the map was zoomed out very far, the app crashed without any message.
When clicking `Search hikes here`, the app takes the bounding box of the OSMDroid map view (of type `BoundingBox`) and converts it to a `Bounds` instance (our own class). However, `Bounds` only accepts valid boundaries. The minimum latitude must be less than or equal to the maximum latitude. Same for longitude.
When the map was zoomed out very far, OSMDroid automatically repeated the world map on the left, right, top and bottom of the screen :
This lead the `BoundingBox` of the map view to be invalid in regards of the `Bounds` criteria, leading to an exception. This is because the map started at some …
> fix(map): fix searching crashing when zoomed out

- app/src/main/java/ch/hikemate/app/model/profile/Profile.kt
- app/src/main/java/ch/hikemate/app/model/profile/ProfileRepository.kt
- app/src/main/java/ch/hikemate/app/model/profile/ProfileRepositoryFirestore.kt
- app/src/main/java/ch/hikemate/app/model/profile/ProfileViewModel.kt
- app/src/test/java/ch/hikemate/app/model/profile/ProfileRepositoryFirestoreTest.kt
- app/src/test/java/ch/hikemate/app/model/profile/ProfileViewModelTest.kt
Added the profile class, view model and repository using Firestore. Also added their tests
The objective was to have a view model and a repository for the user profiles.
For this I also added the `Profile` data class.
The repository is based on its own interface and its implementation relies on Firestore.
Most of the added lines are for tests. Don't be afraid of reviewing this PR :)
> feat(profile): add profile class, vm and repo.

- app/src/main/java/ch/hikemate/app/model/route/HikeRoute.kt
- app/src/main/java/ch/hikemate/app/model/route/HikeRoutesRepositoryOverpass.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/ch/hikemate/app/model/route/HikeRoutesRepositoryOverpassTest.kt
- The objective was to have a name and a description from the OSM API to show to the user, fetched from the API
- Names are not always available. I've tried to implement ways to get a name, using alternative OSM tags and/or combination of tags to create decent name and/or tags, but this doesn't guarantee that a name can be shown AT ALL. 
- Some tags are more relevant than other, thus, there are priorities attributed to tags (For example, the `name` tag weights more than the `operator` tag when looking for a name.
> feat: fetch name and description from overpass API

- app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
This PR introduces a quick fix for a minor bug that was causing Logcat errors when loading the map screen.
We use OSMDroid to display map tiles from OSM as a map view. OSMDroid requires to set an actual user agent for the tiles requests.
The configured user agent was indeed set to a valid value in our code, but it was set **after** the map view was created, meaning the first requests were being sent before the configuration was set, and an error could be seen in Logcat. It did not impact the functionality of the app too much, but is better fixed anyway.
> fix(map): set user agent before OSMDroid map init

- app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
Fixed that the user could scroll out of the world by setting bounds
The user could scroll out of the world and the the map. In this PR I fixed that by setting bounds at the edge of the world.
Note that I also changed the `MAP_MIN_ZOOM` as the previous one did let the user go out of the world by full zooming out
> fix(map): fix map going out of world

- app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest.kt
- app/src/androidTest/java/ch/hikemate/app/navigation/HikeMateAppNavigationTest.kt
- app/src/androidTest/java/ch/hikemate/app/ui/auth/SignInScreenTest.kt
- app/src/androidTest/java/ch/hikemate/app/ui/auth/SignInWithEmailScreenTest.kt
- app/src/main/java/ch/hikemate/app/MainActivity.kt
- app/src/main/java/ch/hikemate/app/model/authentication/AuthViewModel.kt
- app/src/main/java/ch/hikemate/app/ui/auth/SignInScreen.kt
- app/src/main/java/ch/hikemate/app/ui/auth/SignInWithEmailScreen.kt
- app/src/main/java/ch/hikemate/app/ui/components/AppIcon.kt
- app/src/main/java/ch/hikemate/app/ui/navigation/NavigationActions.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/ch/hikemate/app/authentication/AuthViewModelTest.kt
Implemented the sign in with password screen so that a user can sign in without Google.
In this PR I also fixed some typos which were in the same code base as I was working on. I also fixed some old bad practices.
The create account is not implemented yet. You can try to sign in with a fake account which email is
"testing@gmail.com" and password "123123"
I will delete this user as soon as this PR is done. It is not a bad thing for it to exist for now as the user can not create or modify any data.
> feat(auth): implement the sign in screen

- app/src/androidTest/java/ch/hikemate/app/ui/auth/CreateAccountScreenTest.kt
- app/src/androidTest/java/ch/hikemate/app/ui/auth/SignInWithEmailScreenTest.kt
- app/src/main/java/ch/hikemate/app/MainActivity.kt
- app/src/main/java/ch/hikemate/app/model/authentication/AuthRepository.kt
- app/src/main/java/ch/hikemate/app/model/authentication/AuthViewModel.kt
- app/src/main/java/ch/hikemate/app/model/authentication/FirebaseAuthRepository.kt
- app/src/main/java/ch/hikemate/app/ui/auth/CreateAccountScreen.kt
- app/src/main/java/ch/hikemate/app/ui/navigation/NavigationActions.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/ch/hikemate/app/authentication/AuthViewModelTest.kt
Implemented the create account screen so that a user can create an account without Google.
Nothing more to say. The code is quite straightforward.
> feat(auth): implement the create account screen

- app/src/main/java/ch/hikemate/app/model/authentication/FirebaseAuthRepository.kt
By default, Google Sign in limits the sign in to accounts already registered once. This PR fix it
> fix: allow new google accounts to sign up

- app/src/androidTest/java/ch/hikemate/app/ui/auth/SignInScreenTest.kt
- app/src/main/java/ch/hikemate/app/MainActivity.kt
- app/src/main/java/ch/hikemate/app/model/authentication/AuthViewModel.kt
- app/src/main/java/ch/hikemate/app/ui/auth/SignInScreen.kt
Fixed a bug where when a user was logged in, the sign in screen would appear before directing him to the map screen.
I also cleaned up a little bit the `SignInScreen` as it was receiving a useless parameter that was never used.
Also, a lot of changes in `MainActivity` are due to formatting because I made a line longer.
> fix(auth): fix go to map directly when signed in

- app/src/main/java/ch/hikemate/app/model/route/HikeRoutesRepository.kt
- app/src/main/java/ch/hikemate/app/model/route/HikeRoutesRepositoryOverpass.kt
- app/src/main/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModel.kt
- app/src/test/java/ch/hikemate/app/model/route/HikeRoutesRepositoryOverpassTest.kt
- app/src/test/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModelTest.kt
In the saved hikes screen, when we click on one of the hikes in the list, we want to open the details screen for this hike.
However, the saved hikes screen does not have an instance of `HikeRoute`, it only has a `SavedHike`. This does not contain the geographical points of the hike, hence we need to retrieve it somehow.
This PR introduces a function `getRouteById` in the Overpass API repository, along with a `selectRouteById` in the view model that complements `selectRoute`. It takes an ID, retrieves the information of the route and selects it.
The error handling in the view model is part of another task, so it was left on the side for now. Will be done in another PR.
Tests were added for the added functions.
> feat(hikes): add selectRouteById

- app/src/main/java/ch/hikemate/app/model/route/saved/SavedHike.kt
- app/src/main/java/ch/hikemate/app/model/route/saved/SavedHikesRepositoryFirestore.kt
Firebase throws an error when the object to deserialize don't have an empty constructor. This simple PR add a default argument for `SavedHike` and `UserSavedHike`
**Since this PR is needed urgently, the reviewer is allowed to merge it himself after approving**
> fix: firebase can't deserialize saved hikes

- app/src/main/java/ch/hikemate/app/model/route/HikeRoutesRepository.kt
- app/src/main/java/ch/hikemate/app/model/route/HikeRoutesRepositoryOverpass.kt
- app/src/main/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModel.kt
- app/src/test/java/ch/hikemate/app/model/route/HikeRoutesRepositoryOverpassTest.kt
- app/src/test/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModelTest.kt
- The objective is to provide an interface to recover multiple routes from IDs. This PR implements it in the same style as other Overpass requests are implemented.
> Implement a way to get a batch of routes from overpass

- app/build.gradle.kts
- app/src/androidTest/java/ch/hikemate/app/ui/map/MapScreenTest.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
- app/src/main/java/ch/hikemate/app/utils/LocationUtils.kt
- app/src/main/java/ch/hikemate/app/utils/MapUtils.kt
- app/src/main/java/ch/hikemate/app/utils/PermissionUtils.kt
- app/src/main/res/drawable/my_location.xml
- app/src/main/res/drawable/user_location.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/ch/hikemate/app/utils/LocationUtilsTest.kt
- app/src/test/java/ch/hikemate/app/utils/MapUtilsTest.kt
- app/src/test/java/ch/hikemate/app/utils/PermissionUtilsTest.kt
- gradle/libs.versions.toml
This PR introduces two new features :
1. A button to center the map view on the user's location
2. A background loop that displays the current user on the map every 5 seconds to keep it up-to-date
The permission logic is handled as well, with popups to explain the user why those permissions are needed. The app can be used without the permission.
The code of the `MapScreen` composable is becoming very hard to read and understand, I'm sorry for that. I'll see with the SCRUM master if I can be assigned to refactoring this screen's code in a future sprint, because it has become a mess.
In essence, this pull request has two main axes, the two features listed in the summary (center the map, update the user's location periodically).
- A "Center map on me" button was added to the map
- When you …
> feat(map): add user location features

- app/src/main/java/ch/hikemate/app/ui/components/BackButton.kt
The back button would render with a black border in dark mode which would not appear very well.
Used the `MaterialThem.colorScheme.onSurface` instead of the hardcoded one.
> fix: dark mode for back button

- app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest.kt
- app/src/androidTest/java/ch/hikemate/app/navigation/HikeMateAppNavigationTest.kt
- app/src/androidTest/java/ch/hikemate/app/ui/saved/SavedHikesScreenTest.kt
- app/src/main/java/ch/hikemate/app/model/route/saved/SavedHikesViewModel.kt
- app/src/main/java/ch/hikemate/app/ui/components/CenteredErrorAction.kt
- app/src/main/java/ch/hikemate/app/ui/components/CenteredLoadingAnimation.kt
- app/src/main/java/ch/hikemate/app/ui/saved/SavedHikesScreen.kt
- app/src/main/res/values/strings.xml
As part of #132, this PR implements better error handling for the Saved Hikes screen and consequently for the `SavedHikesViewModel`.
There was a bit of refactoring, so a lot of lines might have changed but most of those changes are trivial (renaming, moving, ...).
- Added a `loadingSavedHikes` state to the view model that is set to `true` when saved hikes are being loaded
- Added a `ErrorDisplay` composable to saved hikes for when retrieving saved hikes fails
- Added a `LoadingSavedHikes` composable to saved hikes for when the view model is loading the hikes
Refactoring was made :
- The `SavedHikesScreen` enum was renamed to `SavedHikesSection` to leave space for a `SavedHikesScreen` object
- Test tags were moved into the `SavedHikesScreen` object
Tests were added :
- Test tags were added …
> feat(saved): better error handling

- app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
- app/src/main/java/ch/hikemate/app/model/route/DetailedHikeRoute.kt
- app/src/main/java/ch/hikemate/app/model/route/HikeDifficulty.kt
- app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/ch/hikemate/app/model/route/DetailedHikeRouteTest.kt
This is a refactoring PR that turns the detailed hike's difficulty property type into an `enum` instead of a `String`. It also makes the name of the difficulty level translatable by moving it to the `strings.xml` file.
Not much more to say, this is a quite straight-forward PR.
> refactor(details): hike difficulty as enum

- .github/workflows/ci.yml
Sonar is working on top of the Jacoco report, but doesn't compute it the same way. This upload the report to github actions. 
This PR also adds a small jacoco parser, to show more detailed description in the PR, without having to go all the way to the zip file.
> ci: add jacoco code coverage to the ci

- app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest.kt
- app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest2.kt
- app/src/androidTest/java/ch/hikemate/app/navigation/HikeMateAppNavigationTest.kt
- app/src/androidTest/java/ch/hikemate/app/ui/profile/EditProfileScreenTest.kt
- app/src/androidTest/java/ch/hikemate/app/ui/profile/ProfileScreenTest.kt
- app/src/main/java/ch/hikemate/app/MainActivity.kt
- app/src/main/java/ch/hikemate/app/model/profile/ProfileRepository.kt
- app/src/main/java/ch/hikemate/app/model/profile/ProfileRepositoryFirestore.kt
- app/src/main/java/ch/hikemate/app/model/profile/ProfileViewModel.kt
- app/src/main/java/ch/hikemate/app/model/route/saved/SavedHikesViewModel.kt
- app/src/main/java/ch/hikemate/app/ui/auth/CreateAccountScreen.kt
- app/src/main/java/ch/hikemate/app/ui/auth/SignInScreen.kt
- app/src/main/java/ch/hikemate/app/ui/auth/SignInWithEmailScreen.kt
- app/src/main/java/ch/hikemate/app/ui/components/CenteredErrorAction.kt
- app/src/main/java/ch/hikemate/app/ui/profile/EditProfileScreen.kt
- app/src/main/java/ch/hikemate/app/ui/profile/ProfileScreen.kt
- app/src/main/java/ch/hikemate/app/ui/saved/SavedHikesScreen.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/ch/hikemate/app/model/profile/ProfileViewModelTest.kt
- app/src/test/java/ch/hikemate/app/model/route/saved/SavedHikesViewModelTest.kt
- Error were not correctly handled in the profile view model, this PR implements an error handling with feedback to the user.
- I removed default values since they should not have one now, either we have the correct profile, or we don't and it's an error.
- I changed the `errorMessage` to `errorMessageId`, since it's a string ID
- I changed the way the UI handles the update of the profile, in such a way that we can now detect an error before moving the user back
- I removed a navigation test because it just creates an account, without going through the create profile process (Since he does it using direct firebase function), and thus I don't have a profile to load, which throws an error screen. Such test is in reality a E2E test and is already covered by E2E tests
> feat: improve error handling in profile view model

- .github/workflows/ci.yml
- The objective of this PR is to help with debugging issues that happen only in CI, by providing logcat outputs in the artifacts.
- One difficulty is to ensure that the exit code provided by the tests is not lost during the process, that's why we store it, run logcat, and rethrow it
> ci: add logcat output as artifact in CI

- app/src/main/java/ch/hikemate/app/model/extensions/BoundingBoxExtension.kt
- app/src/main/java/ch/hikemate/app/model/route/HikeRoute.kt
- app/src/main/java/ch/hikemate/app/model/route/HikeRoutesRepositoryOverpass.kt
- app/src/main/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModel.kt
- app/src/test/java/ch/hikemate/app/model/route/HikeRouteTest.kt
- app/src/test/java/ch/hikemate/app/model/route/HikeRoutesRepositoryOverpassTest.kt
- app/src/test/java/ch/hikemate/app/model/route/ListOfHikeRoutesViewModelTest.kt
There was 2 issues about the date line:
1. Searching when showing the date line would make the app crash. For this, I changed it to make 2 requests, one on the left side and one on the right side.
2. Displaying a hike crossing the date line would make the app crash. For this, I filtered out the hikes doing this in the API.
I've not found any hikes in such conditions. This is prevention only.
> fix: date line issues for hikes crossing and searching

- app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
- app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
- app/src/main/java/ch/hikemate/app/ui/theme/Theme.kt
- app/src/main/res/values/strings.xml
The issue was that the calendar had ugly colors. We needed to use the primary color.
As I investigated the issue, I found out we used the wrong `DatePickerDialog`. I changed it to use the compose dialog one.
Also, I updated the them in order to use the primary color app-wide. This changes most of the colors to use the correct one.
> fix: change date picker to compose one

- app/src/main/java/ch/hikemate/app/model/route/Hike.kt
- app/src/main/java/ch/hikemate/app/model/route/HikesViewModel.kt
- app/src/test/java/ch/hikemate/app/model/route/HikesViewModelTest.kt
The code until now had several types and view models to represent hikes, one of the core concepts of the app. As the app grows, we feel the need to assemble those types and view models into a unified system that is easier to use as a single entity, and avoids doing the same computations over and over again.
The objectives are :
- Simplify the code by using only one view model and one type for the hikes
- Avoid duplicate operations
- Improve performance
This PR is gigantic, but there's not much we can do about it, except have several reviewers instead of a single one.
It implements the view model itself, introduces the new `Hike` type, plus a new `DeferredData` type, and provides a lot of tests for the view model.
I will now try to summarize how this view model is intended to work, for the …
> feat(hikes): implement HikesViewModel

- app/src/main/java/ch/hikemate/app/model/route/HikesViewModel.kt
Corrected the name of a parameter in the documentation of `updateHikePlannedDateAsync`, an internal method of `HikesViewModel`. I agree, it's not that important, but it's a very quick fix so I went for it anyway.
> docs(hikes): fix typo in HikesViewModel docs

- app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
- app/src/main/java/ch/hikemate/app/utils/DatetimeUtils.kt
This PR removes `DateTimeUtils.toFormattedDate` and replaces it with `DateTimeUtils.humanReadableFormat`.
`DateTimeUtils.toFormattedDate` used a date format that did not adapt to the current Locale. It used the `dd/MM/yyyy` format, but this format can be mistaken for `MM/dd/yyyy` depending on the date, which can be confusing for English speakers who are used to the second option rather than the first.
> refactor: replace and remove toFormattedDate

- app/build.gradle.kts
- app/src/main/java/ch/hikemate/app/model/facilities/FacilitiesRepositoryOverpass.kt
- app/src/test/java/ch/hikemate/app/model/facilities/FacilitiesRepositoryOverpassTest.kt
- gradle/libs.versions.toml
The facilities repository was using a dependency called `gson`. This works but when we retrieve a lot of data, this library won't handle it and would throw an out of memory error.
To manage this, I changed the facilities repository to use the JSON reader.
> refactor: use jsonReader in facilities repo

- app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest2.kt
- app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
- app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
- app/src/main/res/values/strings.xml
I added a "Run this hike" button to the hike details screen, which lets the user trigger our run this hike feature. Instead of passing the `navigationActions` to the composable which contains the button (`HikeDetails`) to then trigger the navigation to the run hike screen, I've passed a `onRunThisHike` callback, since I believe this makes more sense, so the `HikeDetails` composable does not need to worry about how to implement onRunThisHike at all, and the parent, the `HikeDetailScreen` composable has full control. 
I've changed all test tags in the hike details screen to fit our new naming convention of `{SCREEN}_TEST_TAG_{COMPONENT}` convention. This is since I had to add a new test tag, and it felt a little bit cheeky to add a single one that is conform with our convention, but leave …
> feat: implement run this hike button

- app/src/androidTest/java/ch/hikemate/app/ui/saved/SavedHikesScreenTest.kt
- app/src/main/java/ch/hikemate/app/ui/saved/SavedHikesScreen.kt
Little fix for the `SavedHikes` screen: now a planned hike also appears in the `SavedHikes` screen. This is possible by simply changing the filtering of the `savedHike` in the `savedHikesViewModel`.
> fix: planned hikes also appear in the saved hikes screen

- app/src/main/java/ch/hikemate/app/model/route/DeferredData.kt
- app/src/main/java/ch/hikemate/app/model/route/Hike.kt
- app/src/main/java/ch/hikemate/app/model/route/HikesViewModel.kt
- app/src/test/java/ch/hikemate/app/model/route/DeferredDataTest.kt
- app/src/test/java/ch/hikemate/app/model/route/HikeTest.kt
- app/src/test/java/ch/hikemate/app/model/route/HikesViewModelTest.kt
I'm currently working on using `HikesViewModel` everywhere in the app instead of `ListOfHikeRoutesViewModel` and `SavedHikesViewModel`, however I realize now that I need some more information made available by `HikesViewModel` to make the app work correctly with it.
To this end, I'm doing this intermediate PR to introduce the needed helper functions and new state flows.
Three parts of the code have been modified :
- `DeferredData.kt`: added helper functions
- `Hike.kt`: added helper functions
- `HikesViewModel.kt`: improved implementation and new public members
Tests have been added for `DeferredData` and `Hike`, and the existing ones for `HikesViewModel` were updated to reflect the changes.
- Added `DeferredData.obtained()` as a helper to determine whether an instance represents obtained …
> feat(hikes): new HikesViewModel flows

- app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt
- app/src/androidTest/java/ch/hikemate/app/ui/map/RunHikeScreenTest.kt
- app/src/main/java/ch/hikemate/app/ui/components/BigButton.kt
- app/src/main/java/ch/hikemate/app/ui/components/DetailRow.kt
- app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt
- app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
Added the hike details to the run hike screen bottom sheet as per the Figma design. This includes fetching the elevation data, however this may have to be undone not that the hike classes are unified. Mael agreed to look at this screen once it it merged. Currently, the "current elevation" and "distance progressed" information is hard-coded, since we do not have a location viewModel that provides the UI with location updates. This is being worked on my Rémy.
1. I made the naming structure of the run hike screen test tags more clear, since as adding tests for the new features I noticed in this PR that they were quite convoluted. 
2. When adding the stop this hike button I also improved the back-navigation to be more crash resistant, by making the stop this run button and the back button …
> feat: add details to run hike screen

- app/src/androidTest/java/ch/hikemate/app/ui/profile/DeleteAccountScreenTest.kt
- app/src/main/java/ch/hikemate/app/model/authentication/AuthRepository.kt
- app/src/main/java/ch/hikemate/app/model/authentication/AuthViewModel.kt
- app/src/main/java/ch/hikemate/app/model/authentication/FirebaseAuthRepository.kt
- app/src/main/java/ch/hikemate/app/ui/profile/DeleteAccountScreen.kt
- app/src/test/java/ch/hikemate/app/authentication/AuthViewModelTest.kt
- app/src/test/java/ch/hikemate/app/authentication/FirebaseAuthRepositoryTest.kt
We had an issue that deleting a account **Signed in with Google** would lead to re-authenticate the user. For this it launched an activity on the browser.
This lead to unexpected behaviors such as not working at all with Opera or Firefox for example.
To remediate to this, I changed it to use the in-app re-authentication (like the sign-in) in order to correctly re-authenticate the user.
I also refactored the code in `FirebaseAuthRepository` in order to reduce repeated code. I created the following functions:
- `reauthenticateWithEmailAndPassword` -> re-authentication for an email-account
- `reauthenticateWithGoogleSignIn` -> re-authentication for a google-account
- `getGoogleAuthCredential` -> get the google credential to either sign in or re-authenticate
> fix: re-authenticate the user in-app instead of browser

- app/src/main/java/ch/hikemate/app/ui/saved/SavedHikesScreen.kt
We had a weird UI bug when going from saved to planned hikes. See images:
The issues was arising when having more saved than planned hikes. I fixed this by adding a `Column` with `fillMaxSize` in order to make sure the title and list will take as much space as possible
> fix: ui jump when going from saved to planned

- app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
The last hike of the list was hidden behind the bottom bar. I fixed it by using the padding given my the latter.
> fix: bottom-bar nav overlapping with hikes

- app/src/androidTest/java/ch/hikemate/app/ui/map/MapScreenTest.kt
- app/src/androidTest/java/ch/hikemate/app/ui/map/RunHikeScreenTest.kt
- app/src/main/java/ch/hikemate/app/ui/components/LocationPermissionAlertDialog.kt
- app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
- app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
- app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
- app/src/main/java/ch/hikemate/app/utils/LocationUtils.kt
- app/src/main/java/ch/hikemate/app/utils/MapUtils.kt
- app/src/test/java/ch/hikemate/app/utils/MapUtilsTest.kt
- **Objective:** Enhance user location handling on run hike screen and map centering functionality
- **Implementation:** Refactored `RunHikeScreen.kt`, `MapUtils.kt`, and related utility classes to improve location permissions, map interaction, and user experience
**Code Changes:**
- Added a new button to center the map on the user's location
- Introduced a comprehensive location permission handling mechanism
- Implemented location update management in the `RunHikeScreen`
- Renamed `centerMapOnUserLocation` to `centerMapOnLocation` to support more flexible location centering
- Updated related test files to reflect the new implementation
The changes focus on improving the user's ability to interact with the map during a hike:
- Enhanced location tracking and permission management
- …
> feat: project user location on hike in run hike

- app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
When using the run hikes screen, updating the user's location every 5 seconds is a bit slow, does not feel smooth. We empirically observed that a delay of `500` milliseconds is fine in terms of performance and provides a way better user experience in terms of smoothness.
> feat: increase location updates freq

- app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
- app/src/main/res/values/strings.xml
As stated by the coaches, when the button is "Un-plan this hike", it should be in a red color to show the user it's not the same type of action as planning a hike.
I also added a little improvement: when showing the dialog, the default day would be the planned date if set. This make the button "Un-plan this hike" by default.
> fix: unplan this hike color

- app/src/androidTest/java/ch/hikemate/app/ui/profile/DeleteAccountScreenTest.kt
- app/src/main/java/ch/hikemate/app/ui/components/BackButton.kt
- This PR simply removes the ability to multi go back by multi clicking on the back button.
- Clicking too fast on the BackButton would trigger multiple goBack, and raise logical issues
> fix: fix back buttons double clicks

- app/src/androidTest/java/ch/hikemate/app/ui/map/RunHikeScreenTest.kt
- app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
- app/src/main/java/ch/hikemate/app/utils/LocationUtils.kt
- app/src/main/java/ch/hikemate/app/utils/RouteUtils.kt
- app/src/main/res/values/strings.xml
- app/src/test/java/ch/hikemate/app/utils/LocationUtilsTest.kt
The current elevation and progress were fake in the run hike screen. This PR changed this to display the actual progression and user elevation.
To get the elevation of the user, I retrieve the elevation of the **starting point of the segment on which the user is projected on**. This is some sort of estimation but is way faster than actually retrieving the elevation of the user from the API.
> feat: display actual progression and user elevation in run

- app/src/main/java/ch/hikemate/app/ui/components/WithDetailedHike.kt
- app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
- app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt
- This fixes #299 where a user could be stuck in a soft loop in case their internet was not working, while trying to go on the HikeDetails screen.
- This does the same thing on the RunHikeScreen, even though the bug should never happen here since we already have the details
Paths to recreate the bug:
- Online search for hikes.
- Disable your internet connection.
- Try to go to the HikeDetailsScreen of a Hike.
- User is stuck
This now adds a BackButton for the user to escape.
> fix: add a back button on HikeDetails and RunHike loading screen

- app/src/androidTest/java/ch/hikemate/app/ui/map/MapScreenTest.kt
- app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
- app/src/main/java/ch/hikemate/app/utils/MapUtils.kt
It was previously very hard to know which end of the hike was the start or the end of it. For this, I added a little circle at the start of it.
We could discuss if this could still be confusing for the user as he could believe this is the end of the hike.
Before:
After:
> feat: display the starting of a hike

- app/src/main/java/ch/hikemate/app/model/route/HikesViewModel.kt
- app/src/test/java/ch/hikemate/app/model/route/HikesViewModelTest.kt
There was a bug when the user went to the saved screen and opened a hike's details. If the user then unsaved the hike, it removed the hike from the loaded hikes, thus unselected then hike, and thus kicked the user out of the details screen.
This bug was "by design" in the sense that the HikesViewModel was built with the idea that when the selected hike is unloaded, it must be unselected as well. But this does not make sense from a practical point of view.
This commit corrects the design of HikesViewModel and its tests to let the user unsave the hike freely.
> fix(hikes): unsaving hike in details

- app/src/androidTest/java/ch/hikemate/app/navigation/BottomBarNavigationTest.kt
- app/src/main/java/ch/hikemate/app/ui/navigation/BottomBarNavigation.kt
- Fixes a UI Glitch bug when clicking on currently selected bottom navigation item 
- When the user clicked on the current selected bottom navigation item, the navigation actions are triggered and re-render the screen, which leads to a UI glitch. 
- I fixed it by making the navigation actions be triggered only when needed
https://github.com/user-attachments/assets/f785d91e-7142-4dc1-8856-7208c11a3e9e
https://github.com/user-attachments/assets/204b735a-1497-440f-9f9e-63a3bd5b2816
> fix: ui glitching when clicking on already selected bottom item

- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
We had un-used data in `Color.xml` and `Strings.xml`. This PR removes them.
> fix: remove unused-data in xml
