HikeMate/hikeMateApp

README.md
I added the project description from the docs document in the README.md. I also changed it to markdown so that it looks good.
=> chore: add project description to the README.md

.github/workflows/ci.yml
- Fix the #17 issue
- CI wasn't running on all branches, leading to issues when needing to see if Sonar detects issues
=> fix(ci): run ci on all branches

.github/workflows/artifact_building.yml
Added the workflow required by the M1 milestone to produce the APK
=> ci: add a workflow to build an APK

.github/workflows/artifact_building.yml
- Fix use of deprecated actions
=> ci: fix the use of a deprecated action for upload

.github/workflows/artifact_building.yml, .github/workflows/ci.yml, app/build.gradle.kts
- Changed the gradle configuration to sign the APK on a release
=> ci: add signing the APK to the workflow

app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
Added a function to show a hike on the map using a Polyline.
The objective was to show a mock hike on the map as a line. For now, I display 3 mock routes on the map.
There are no tests on the `onClick` of the line as there are no ways to retrieve a line on the map (no test tag for example)
=> feat(map): show hikes on the map

app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest.kt
The objective of this PR is to create a full and complete **end to end test** in order to test the app as a real user.
This is done using `composeTestRule` and checking for `TEST_TAGs` throughout the app.
=> test(end2end): first end2end test with basic nav

app/src/androidTest/java/ch/hikemate/app/ui/map/MapScreenTest.kt, app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
- Searching for hikes were occurring instantly when retrieved from the cache. This commit introduces an artificial delay to simulate fetching the data correctly
=> fix: add delay to instantaneous hike's search

app/src/main/java/ch/hikemate/app/ui/theme/Theme.kt
The color of the status bar was purple. I changed it to match the background color (white or black depending if dark mode is activated or not)
=> fix(ui): fix status bar color

staff-feedback/M1.md
Update the grading (with rebasing the branch)
Closes #108
=> fix: update m1 grading with correct one

app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest.kt, app/src/androidTest/java/ch/hikemate/app/navigation/HikeMateAppNavigationTest.kt
Fixed the navigation and end2end tests using the new sign in with email feature.
For this I used `Thread.sleep(1000)` in order to make sure the user is signed in. If you have a better idea I would love to here about it. I made sure to make this check as least as possible (only 1 per test) in order to not make the CI run for too long.
=> fix(test): fix nav and end2end tests

app/src/main/java/ch/hikemate/app/ui/auth/SignInScreen.kt
Fixed signing in with Google which would not lead to the map screen.
=> fix(auth): fix sign in with google

app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt, app/src/main/java/ch/hikemate/app/ui/components/HikeCard.kt, app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt, app/src/main/java/ch/hikemate/app/ui/saved/SavedHikesScreen.kt
The goal was to remove any dummy data for the MS2 milestone
I removed some dummy data and put a real graph in the hike details screen.
Sonar might complain, it's ok. We will put everything back after the Ms2
=> chore: remove all dummy data

app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest2.kt
Implements a second meaningful end-to-end test that saves a hike in the details screen and checks it has indeed been saved.
=> test(end2end): implement second end2end

app/src/main/java/ch/hikemate/app/model/route/HikeRoute.kt, app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt, app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt, app/src/main/java/ch/hikemate/app/ui/theme/Color.kt, app/src/test/java/ch/hikemate/app/model/route/HikeRouteTest.kt
Implemented a deterministic color for each hikes so that the color won't change.
For this, I get the hash of the id modulo it to get the index of the color to use. The colors are hardcoded and selected by me so that they look good and enough so that there are not too much crossing of hikes of the same color.
=> feat(routes): deterministic color for hikes

app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest2.kt, app/src/androidTest/java/ch/hikemate/app/ui/map/HikeDetailsScreenTest.kt, app/src/androidTest/java/ch/hikemate/app/ui/map/MapScreenTest.kt, app/src/androidTest/java/ch/hikemate/app/ui/map/ZoomMapButtonTest.kt, app/src/main/java/ch/hikemate/app/MainActivity.kt, app/src/main/java/ch/hikemate/app/ui/components/AsyncStateHandler.kt, app/src/main/java/ch/hikemate/app/ui/components/GenericErrorHandler.kt, app/src/main/java/ch/hikemate/app/ui/components/HikeCard.kt, app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt, app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
The goal was to have a message displaying and telling the user if the hike is suitable or not for him.
As I added this feature, multiple things had to be done:
- Needed for the profile informations in `MapScreen` and `HikeDetailScreen`
- Needed to fix tests using those screens (as they now need a valid profile
- Needed to fix end-to-end 2 test as it was not creating a profile and still going to map screen
=> feat(routes): display the appropriateness message

app/src/androidTest/java/ch/hikemate/app/ui/map/RunHikeScreenTest.kt, app/src/main/java/ch/hikemate/app/MainActivity.kt, app/src/main/java/ch/hikemate/app/model/facilities/FacilitiesRepositoryOverpass.kt, app/src/main/java/ch/hikemate/app/model/overpassAPI/OverpassRepository.kt, app/src/main/java/ch/hikemate/app/ui/map/HikeDetailScreen.kt, app/src/main/java/ch/hikemate/app/ui/map/RunHikeScreen.kt, app/src/main/java/ch/hikemate/app/ui/navigation/NavigationActions.kt
Added a bare minimum run hike screen, so that all other run hike screen tasks have something to work with. Everything that is currently missing has a different task, which takes care of it.
FYI, I also made some very minor fixes to the facilities repo which I just noticed while playing around with the code during dev.
=> feat:implement run hike screen skeleton

app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt
This pull request includes changes to the `HikeDetailScreen` in the `HikeDetailsScreen.kt` file to improve the handling of the back button functionality.
Back button handling improvements:
Moving it to the correct place to have it work in all cases.
=> fix: back handler in hike details not in the right place

app/src/main/java/ch/hikemate/app/model/route/Hike.kt, app/src/main/java/ch/hikemate/app/model/route/HikesViewModel.kt, app/src/main/java/ch/hikemate/app/model/route/saved/SavedHike.kt, app/src/main/java/ch/hikemate/app/model/route/saved/SavedHikesViewModel.kt, app/src/test/java/ch/hikemate/app/model/route/HikeTest.kt
As I was doing #252 , I found out that `SavedHikesRepository` didn't allow nullable names. I changed that in order to have a possibility to have nullable name.
=> chore: handle nullable name in saved hike repo

app/src/androidTest/java/ch/hikemate/app/benchmark/LocationProjectionBenchmark.kt, app/src/main/java/ch/hikemate/app/model/route/Hike.kt, app/src/main/java/ch/hikemate/app/utils/LocationUtils.kt, app/src/test/java/ch/hikemate/app/model/route/HikeTest.kt, app/src/test/java/ch/hikemate/app/utils/LocationUtilsTest.kt
Adapted the `LocationUtils`.`projectLocationOnHike` to the new code and the new `DetailedHike` type.
This simple change is necessary for the previous functionality of the function and since the code now accepts `DetailedHike` as a value instead of `HikeRoute`.
=> fix: adapt Hike.kt and DetailedHike to the projection function

app/src/androidTest/java/ch/hikemate/app/endtoend/EndToEndTest3.kt, app/src/main/java/ch/hikemate/app/ui/components/HikeCard.kt, app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt, app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
This is the third end-2-end test.
This test will:
- Create an account
- Arrive on map screen
- Go to tutorial page
- Search for the "Your HikeMate Profile" section
- Open the section
- Search for the "Go to Profile screen" button
- Click on the button
- When on profile, click on edit profile
- Change the name and the hiking level to "Expert"
- Get back to profile
- Check that the profile is up-to-date
=> test: End2End 3 about tutorial and profile

app/src/main/java/ch/hikemate/app/ui/map/HikeDetailsScreen.kt, app/src/main/java/ch/hikemate/app/ui/map/MapScreen.kt
This PR is simply refactoring to reduce code complexity on functions flagged by Sonar
=> Chore: refactor to reduce code complexity

app/src/main/java/ch/hikemate/app/ui/profile/EditProfileScreen.kt
To reproduce this bug, you have to:
- Sign in as a user
- Disable internet on the device
- Edit the profile (IMPORTANT: you have to actually change it.)
- Save the profile
I added a delay of **5 seconds** to force the user to go back. This will still update the user in firebase as the task was launched.
=> fix: offline update profile, add timeout to go back.

app/src/main/res/values/strings.xml
Instead of "-" Display "You're too far from the hike!"
=> feat: display message when too far
